set_property SRC_FILE_INFO {cfile:h:/FPGA/ZYNQ_PSPL/X_Ubuntu_lcd/X_Ubuntu/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_processing_system7_0_0/ps_pl_hdmi_processing_system7_0_0.xdc rfile:../X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_processing_system7_0_0/ps_pl_hdmi_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:zynq_sys/ps_pl_hdmi_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA/ZYNQ_PSPL/X_Ubuntu_lcd/X_Ubuntu/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_clk_wiz_0_0/ps_pl_hdmi_clk_wiz_0_0.xdc rfile:../X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_clk_wiz_0_0/ps_pl_hdmi_clk_wiz_0_0.xdc id:2 order:EARLY scoped_inst:zynq_sys/ps_pl_hdmi_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA/ZYNQ_PSPL/X_Ubuntu_lcd/X_Ubuntu/X_Ubuntu.srcs/sources_1/ip/clk_lvds/clk_lvds.xdc rfile:../X_Ubuntu.srcs/sources_1/ip/clk_lvds/clk_lvds.xdc id:3 order:EARLY scoped_inst:lvds_ins_u0/clk_pll_lvds/inst} [current_design]
set_property SRC_FILE_INFO {cfile:H:/FPGA/ZYNQ_PSPL/X_Ubuntu_lcd/X_Ubuntu/X_Ubuntu.srcs/constrs_1/new/ps_pl_hdmi.xdc rfile:../X_Ubuntu.srcs/constrs_1/new/ps_pl_hdmi.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA/ZYNQ_PSPL/X_Ubuntu_lcd/X_Ubuntu/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0_clocks.xdc rfile:../X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0_clocks.xdc id:5 order:LATE scoped_inst:zynq_sys/ps_pl_hdmi_i/v_axi4s_vid_out_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA/ZYNQ_PSPL/X_Ubuntu_lcd/X_Ubuntu/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0_clocks.xdc rfile:../X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0_clocks.xdc id:6 order:LATE scoped_inst:zynq_sys/ps_pl_hdmi_i/v_tc_0/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.21
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:SCOPED_XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.2
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[3]}]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[2]}]
set_property src_info {type:XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[1]}]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[0]}]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {pl_led4_tri_o[0]}]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {pl_led4_tri_o[1]}]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {pl_led4_tri_o[2]}]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {pl_led4_tri_o[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells COUPLER_INST/FIFO_INST/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells COUPLER_INST/FIFO_INST/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_axi4s_vid_out_0/inst/vid_io_out_clk]]]
set_property src_info {type:SCOPED_XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells COUPLER_INST/FIFO_INST/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells COUPLER_INST/FIFO_INST/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_axi4s_vid_out_0/inst/aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_tc_0/U0/clk]] -to [all_registers -clock [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_tc_0/U0/s_axi_aclk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_tc_0/U0/clk]]]
set_property src_info {type:SCOPED_XDC file:6 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_tc_0/U0/s_axi_aclk]] -to [all_registers -clock [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_tc_0/U0/clk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins zynq_sys/ps_pl_hdmi_i/v_tc_0/U0/s_axi_aclk]]]
